Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  scope() do
    resources :pet_profiles, path: "pet-profiles" do
      resources :supplies, only: [ :index, :create, :show, :new ]
      resources :appointments, only: [ :index, :create, :show, :new ]
      resources :tasks, only: [ :index, :new, :create ]
      # resources :tasks, shallow: true # only: [ :index, :new, :create ]
    end
  end
  resources :supplies, only: [ :index, :show, :edit, :update, :destroy ]
  resources :appointments, only: [ :index, :show, :edit, :update, :destroy ]
  resources :tasks, only: [ :index, :show, :edit, :update, :destroy ]
  # generated by shallow: true - resources :tasks, only: [ :show, :edit, :update, :destroy ]
  # Defines the root path route ("/")
  root "pet_profiles#index"
end
